/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Page_accueil (void);
GtkWidget* create_gestion_de_reclamation (void);
GtkWidget* create_ajoutdereclamation (void);
GtkWidget* create_CONFIRMATION (void);
GtkWidget* create_modification (void);
GtkWidget* create_ajouter_user (void);
GtkWidget* create_afficher_user (void);
GtkWidget* create_supprimer1_user (void);
GtkWidget* create_modifier1_user (void);
GtkWidget* create_auth_user (void);
GtkWidget* create_inscri_user (void);
GtkWidget* create_afiicher_st (void);
GtkWidget* create_ajouter_st (void);
GtkWidget* create_supprimer_st (void);
GtkWidget* create_modifier_st (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_choices (void);
GtkWidget* create_addmenu (void);
GtkWidget* create_deletemenu (void);
GtkWidget* create_browsemenu (void);
GtkWidget* create_window1 (void);
GtkWidget* create_updatemenu (void);
GtkWidget* create_window1_foyer (void);
GtkWidget* create_principale (void);
GtkWidget* create_modifier (void);
GtkWidget* create_window2_tableau (void);
GtkWidget* create_window2 (void);
